import blessed
term = blessed.Terminal()
DIRECTIONS = { # movement controls
        'KEY_UP' : (0, -1),
        'up' : (0, -1),
        'KEY_KP_8' : (0, -1),
        '8' : (0, -1),
        'KEY_DOWN' : (0, 1),
        'down' : (0, 1),
        'KEY_KP_2' : (0, 1),
        '2' : (0, 1),
        'KEY_LEFT' : (-1, 0),
        'left' : (-1, 0),
        'KEY_KP_4' : (-1, 0),
        '4' : (-1, 0),
        'KEY_RIGHT' : (1, 0),
        'right' : (1, 0),
        'KEY_KP_6' : (1, 0),
        '6' : (1, 0),
        'KEY_PGDOWN' : (1, 1),
        'KEY_LR' : (1, 1),
        'KEY_KP_3' : (1, 1),
        '3' : (1, 1),
        'KEY_PGUP' : (1, -1),
        'KEY_KP_9' : (1, -1),
        '9' : (1, -1),
        'KEY_END' : (-1, 1),
        'KEY_SELECT' : (-1, 1),
        'KEY_KP_1' : (-1, 1),
        '1' : (-1, 1),
        'KEY_HOME' : (-1, -1),
        'KEY_FIND' : (-1, -1),
        'KEY_KP_7' : (-1, -1),
        '7' : (-1, -1),
}

